// <auto-generated />
using System;
using CertificateApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CertificateApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428220000_ConvertStudiedDatesToDate")]
    partial class ConvertStudiedDatesToDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CertificateApp.Models.CertificateOfAttendance", b =>
                {
                    b.Property<string>("StudentID")
                        .HasColumnType("text");

                    b.Property<string>("AcademicYear")
                        .HasColumnType("text");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BornDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StudiedFrom")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("StudiedTo")
                        .HasColumnType("date");

                    b.Property<string>("Year")
                        .HasColumnType("text");

                    b.HasKey("StudentID");

                    b.ToTable("CertificateOfAttendance", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
